apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: utility-api
  template:
    metadata:
      labels:
        app: utility-api
    spec:
      containers:
        - name: utility-api
          image: pavanelthepu/utility-api
          ports:
            - containerPort: 9060
          resources:
            requests:
              memory: "20Mi"
              cpu: "0.25"
            limits:
              memory: "400Mi"
              cpu: "1"
