apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Retain
allowVolumeExpansion: true
---
# Note: This PVC is for reference only. The actual PVCs are created by the StatefulSet's volumeClaimTemplates
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc-example
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-storage
  resources:
    requests:
      storage: 10Gi