apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    app: fluentd
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/mongodb-*.log
      pos_file /var/log/fluentd-mongodb.pos
      tag mongodb
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter mongodb.**>
      @type parser
      key_name log
      <parse>
        @type regexp
        expression /^(?<time>[^ ]* [^ ]*) (?<severity>[^ ]*) (?<component>[^ ]*) \[(?<context>[^\]]+)\] (?<message>.*)/
        time_format %Y-%m-%dT%H:%M:%S.%L
      </parse>
      reserve_data true
    </filter>

    <match mongodb.**>
      @type elasticsearch
      host elasticsearch-client.monitoring
      port 9200
      logstash_format true
      logstash_prefix mongodb
      <buffer>
        @type file
        path /var/log/fluentd-buffers/mongodb
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever false
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-mongodb
  labels:
    app: fluentd-mongodb
spec:
  selector:
    matchLabels:
      app: fluentd-mongodb
  template:
    metadata:
      labels:
        app: fluentd-mongodb
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch-client.monitoring"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-config