apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  init-replica.js: |
    rs.initiate(
      {
        _id: "rs0",
        version: 1,
        members: [
          { _id: 0, host: "mongodb-0.mongodb-headless.default.svc.cluster.local:27017" },
          { _id: 1, host: "mongodb-1.mongodb-headless.default.svc.cluster.local:27017" },
          { _id: 2, host: "mongodb-2.mongodb-headless.default.svc.cluster.local:27017" }
        ]
      }
    )
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
      replSetName: rs0
    security:
      authorization: disabled