apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-exporter-config
  labels:
    app: mongodb-exporter
data:
  mongodb-exporter.yml: |
    mongodb:
      uri: "mongodb://mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017,mongodb-2.mongodb-headless.default.svc.cluster.local:27017/?replicaSet=rs0"
    collect_all:
      mode: "full"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.20
        args:
        - --config.file=/etc/mongodb-exporter/mongodb-exporter.yml
        - --web.listen-address=:9216
        ports:
        - containerPort: 9216
          name: metrics
        volumeMounts:
        - name: config
          mountPath: /etc/mongodb-exporter
      volumes:
      - name: config
        configMap:
          name: mongodb-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  ports:
  - port: 9216
    targetPort: 9216
    name: metrics
  selector:
    app: mongodb-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
    release: prometheus
spec:
  endpoints:
  - port: metrics
    interval: 30s
  selector:
    matchLabels:
      app: mongodb-exporter